In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a vector of length 5 with random integers between 0 and 10
vector = np.random.randint(0, 11, 5)
vector

array([5, 6, 2, 3, 4])

In [4]:
# Create a vector with values ranging from 15 to 55
vector = np.arange(15, 56)
vector[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [6]:
# Create a random array with 1000 elements
array = np.random.rand(1000)
array

array([6.13338584e-01, 2.23162891e-01, 8.74550697e-01, 5.81156518e-01,
       4.41752482e-01, 7.32650102e-01, 7.87507184e-01, 5.08237013e-01,
       4.79348962e-01, 8.95518301e-01, 8.13183504e-01, 8.26167619e-01,
       1.15592079e-01, 7.78772463e-02, 2.03955964e-01, 1.75100319e-01,
       3.61342456e-01, 9.40979869e-01, 4.39434578e-01, 5.08516332e-01,
       6.20314360e-01, 8.12168069e-01, 4.93698046e-01, 4.36405591e-01,
       6.33198895e-01, 5.47610014e-01, 9.01880762e-01, 2.95574622e-01,
       2.33831547e-03, 7.96053691e-01, 7.23144561e-01, 5.18982906e-03,
       5.17658351e-01, 9.30983398e-01, 7.29023562e-01, 9.57909733e-01,
       7.64584845e-01, 2.37927154e-01, 7.12777628e-01, 7.22701124e-01,
       8.10793497e-01, 4.13060469e-01, 6.52015992e-01, 6.77180614e-01,
       3.04832964e-01, 1.00295214e-01, 2.91951504e-01, 9.29752851e-01,
       1.83706309e-01, 7.93811194e-01, 8.86681605e-01, 1.88629256e-01,
       9.08387952e-01, 1.50606617e-01, 9.58335095e-01, 9.25703665e-01,
      

In [7]:
# Compute the average, variance, and standard deviation of the array elements
avg = np.mean(array)
var = np.var(array)
std = np.std(array)

In [10]:
avg

0.5031651005921298

In [12]:
var

0.08410434185529954

In [11]:
std

0.29000748586079556

In [14]:
# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Calculate the cumulative sum along axis 0 (rows)
cumulative_rows = np.cumsum(arr, axis=0)

# Calculate the sum over rows for each of the 3 columns
sum_cols = np.sum(arr, axis=0)

# Calculate the cumulative sum along axis 1 (columns)
cumulative_cols = np.cumsum(arr, axis=1)

# Calculate the sum over columns for each of the 2 rows
sum_rows = np.sum(arr, axis=1)

In [15]:
cumulative_rows

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [16]:
cumsum_cols

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)